<style>
    /* ----------  PRINT ONLY – sirf blank-page fix  ---------- */
   @media print {
		/* --- Common flex fix --- */
		.row.pagebreak,
		.d-flex,
		.flex-stack,
		.flex-wrap {
			display: block !important;
			width: 100% !important;
		}

		/* --- Page break control --- */
		.row.pagebreak {
			page-break-after: always !important;
			break-after: page !important;
			margin: 0 !important;
			padding: 0 !important;
		}

		.row.pagebreak:last-of-type {
			page-break-after: auto !important;
			break-after: auto !important;
		}

		/* --- Prevent unwanted blank pages --- */
		* {
			page-break-before: auto !important;
			page-break-inside: avoid !important;
		}

		/* agar empty row ho to page-break hata do */
		.row.pagebreak:empty {
			display: none !important;
			page-break-after: auto !important;
			break-after: auto !important;
		}

		/* button hide */
		.btn, .no-print {
			display: none !important;
		}
		/* * {
			outline: 1px solid red !important;
		} */
	}

    /* ----------  screen ke liye kuch change nahi  ---------- */
</style>
	
	<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
		<!--begin::Post-->
		<div class="post d-flex flex-column-fluid" id="kt_post">
			<!--begin::Container-->
			<div id="kt_content_container" class="container-xxl">
				<!-- begin::Invoice 3-->
				<div class="card" style="border:none;">
					<!-- begin::Body-->
					<div class="card-body py-2">
						<div class="row">
							<!-- ========================================================= -->
							<!--  PAGE 1  –– full-page background  (xyz.png)             -->
							<!-- ========================================================= -->
							<!-- ========================================================= -->
							<!--  PAGE 1  –– full-page background  (0.jpg)               -->
							<!-- ========================================================= -->
							<div class="row pagebreak" 
								style="position:relative; width:210mm; height:297mm; margin:0 auto 10mm; page-break-before:always;
										background-image: url('<?php echo base_url()?>assets/media/qutation-design/1.jpg');
										background-size: cover;
										background-position: center;
										background-repeat: no-repeat;">

								<!-- ✅ Text content on top of background -->
								<div style="position: relative; z-index: 2; padding: 40px;">
									<div class="text-sm col-5">
										<table class="text-muted table-responsive table" style="width:100%;">
											<tr>
												<!-- Quotation date -->
												<td style="position: relative; z-index: 2;
															padding: 236px 0px 0px 74px;
															color: black;
															font-size: 13px;">
													<?php echo date('d-m-Y', strtotime($data_info->qauote_date)); ?>
												</td>
											</tr>

											<!-- Quotation No. -->
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 4px 0 0 563px;">
													<div style="position: relative; top: -20px;
																color: black;
																font-size: 13px;">
													<?php echo $data_info->reference_no??"________"; ?>
													</div>
												</td>
											</tr>

											<!-- Generated by -->
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 5px 0 0 143px;">
													<div style="position: relative; top: -4px;
																color: black;
																font-size: 13px;">
													<?php echo $franchisee->franchisee_code?? "_______"; ?>
													</div>
												</td>
											</tr>
										</table>
										<!-- customer Details  -->					
										<table class="text-muted table-responsive table" style="width:100%;">
											<!-- Client name  -->
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 100px 2px 0 98px;
															color: black;
															font-size: 15px;">
													<?php echo $client->client_name??'_________';?>
												</td>
											</tr>

											<!-- client email id  -->
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 9px 2px 0 113px;
															color: black;
															font-size: 15px;">
													<?php echo $client->client_email??'________';?>
												</td>
											</tr>

											<!-- client phone number  -->
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 8px 2px 0 163px;
															color: black;
															font-size: 15px;">
													<?php echo $client->phone??'________';?>
												</td>
											</tr>

											<!-- Client Address -->
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 6px 149px 1px 143px;
															color: black;
															font-size: 15px;
															white-space: nowrap;
															overflow: hidden;
															text-overflow: ellipsis;">
													<?php echo $client->address??'________'; ?>
												</td>
											</tr>
										</table> 

										<!-- Vendor details  -->
										<table class="text-muted table-responsive table" style="width:100%;">
											
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 108px 0px 0px 172px;
															color: black;
															font-size: 15px;
															white-space: nowrap;
															overflow: hidden;
															text-overflow: ellipsis;">
													<?php echo $vendor->vendor_name??'________';?>
												</td>
											</tr>
											<!-- Authorization state  -->
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 21px 0px 0px 172px;
															color: black;
															font-size: 15px;
															white-space: nowrap;
															overflow: hidden;
															text-overflow: ellipsis;">
													<?php echo $vendor->state_name??'________';?>
												</td>
											</tr>
											<!-- vendor address  -->
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 14px 0px 0px 172px;
															color: black;
															font-size: 15px;
															white-space: nowrap;
															overflow: hidden;
															text-overflow: ellipsis;">
													<?php 
														echo $vendor->address ?? '_______';
													?>
												</td>
											</tr>
											<!-- GTIN Number -->
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 27px 0px 0px 172px;
															color: black;
															font-size: 15px;
															white-space: nowrap;
															overflow: hidden;
															text-overflow: ellipsis;">
													<?php echo $vendor->gstin_number ?? '_______';?>
												</td>
											</tr>
											<tr>
												<td style="position: relative; z-index: 2;
															padding: 25px 0px 0px 232px;
															color: black;
															font-size: 15px;
															white-space: nowrap;
															overflow: hidden;
															text-overflow: ellipsis;">
													<?php echo $vendor->account_number ?? '________ ';
													?>
												</td>
											</tr>
										</table>
									</div>
								</div>
							</div>

							<!-- ========================================================= -->
							<!--  PAGE 2  –– full-page background project description      -->
							<!-- ========================================================= -->
							<div class="row pagebreak" style="position:relative;width:210mm;height:297mm;margin:0 auto 10mm;page-break-before:always;">
								<img src="<?php echo base_url()?>assets/media/qutation-design/2.jpg"
									style="position:absolute;top:0;left:0;width:100%;height:100%;object-fit:cover;">
								<!-- =====  put your custom content here  ===== -->
								<table class="text-muted table-responsive table" style="width:100%;">
									<!-- Project Name  -->
									<tr>
										<td style="position: relative; z-index: 2;
													padding: 257px 2px 0 126px;
													color: black;
													font-size: 15px;">
											<?php echo $project->project_name??'__________________________________________________';?>
										</td>
									</tr>
									<!-- Project Size  -->
									<tr>
										<td style="position: relative; z-index: 2;
													padding: 9px 1px 669px 185px;
													color: black;
													font-size: 15px;">
											<?php echo $project->qty.'KW' ?? '_________';?> 
										</td>
									</tr>

									<!-- Project type  -->
									<tr>
										<td style="position: relative; z-index: 2;
													padding: 0 1px 0 194px;
													color: black;
													font-size: 15px;">
											<div style="position: relative; top: -663px;">
											<?php echo $project->project_type ??' ________'; ?>
											</div>
										</td>
									</tr>
									<!-- Project Price  -->
									<tr>
										<td style="position: relative; z-index: 2;
													padding: 0 1px 0 194px;
													color: black;
													font-size: 15px;">
											<div style="position: relative; top: -643px;">
											<?php echo $project->basic_rate??'______'; ?>
											</div>
										</td>
									</tr>
									<!-- Project Total cost  -->
									<tr>
										<td style="position: relative; z-index: 2;
													padding: 0 1px 0 214px;
													color: black;
													font-size: 15px;">
											<div style="position: relative; top: -634px;">
											<?php echo $project->amount??'_______'; ?>
											</div>
										</td>
									</tr>
									<!-- Project scope -->
									<tr>
										<td style="position: relative; z-index: 2;
													padding: 1px 1px 0 188px;
													color: black;
													font-size: 15px;">
											<div style="position: relative; top: -617px;">
											<?php echo $data_info->work_scope??' NA'; ?>
											</div>
										</td>
									</tr>

									<!-- Project specification -->
									<tr>
										<td style="position: relative; z-index: 2;
													padding: 1px 1px 0 240px;
													color: black;
													font-size: 15px;">
											<div style="position: relative; top: -594px;">
											<?php echo $data_info->specification?? 'NA'; ?>
											</div>
										</td>
									</tr>
								</table> 
							</div>

							<!-- ========================================================= -->
							<!--  PAGE 3  –– full-page background  (xyz.png)             -->
							<!-- ========================================================= -->
							<div class="row pagebreak" style="position:relative;width:210mm;height:297mm;margin:0 auto 10mm;page-break-before:always;">
								<img src="<?php echo base_url()?>assets/media/qutation-design/3.jpg"
									style="position:absolute;top:0;left:0;width:100%;height:100%;object-fit:cover;">
								<!-- =====  put your custom content here  ===== -->
							</div>

							<!-- ========================================================= -->
							<!--  PAGE 4  –– full-page background  Project Material detail -->
							<!-- ========================================================= -->
							<div class="row pagebreak"
								style="position:relative;width:210mm;height:297mm;margin:0 auto 10mm;page-break-before:always;">

								<!-- background image -->
								<img src="<?php echo base_url()?>assets/media/qutation-design/4.jpg"
									style="position:absolute;top:0;left:0;width:100%;height:100%;object-fit:cover;z-index:1;">

								<!-- =====  put your custom content here  ===== -->
								<table class="text-muted table-responsive table" style="width:100%;position:relative;z-index:2;">
									<!-- Project Type  -->
									<tr>
										<td style="position: relative;
												padding: 282px 2px 0 163px;
												color: black;
												font-size: 15px;">
											<?php echo $project->project_type??'________';?>
										</td>
									</tr>
									<!-- Product type  -->
									<tr>
										<td style="position: relative;
												padding: 0px 1px 787px 168px;
												color: black;
												font-size: 15px;">
												<div style="position: relative; top: 10px;">
													<?php echo $products[0]->product_type ?? 'My-type';?>
												</div>
											
										</td>
									</tr>
								</table>

								<!-- TABLE OVERLAY -->
								<div class="table-responsive" style="position:absolute; top:423px;left:0;right:0;z-index:3;height:630px;">
									<table class="table table-bordered align-middle mb-0" style="font-size:11px;">
										<thead class="table-light" style="font-size:11px;">
											<tr>
												<th style="padding:4px 6px;font-size:11px;">No.</th>
												<th style="padding:4px 6px;font-size:11px;">Product Name</th>
												<th style="padding:4px 6px;font-size:11px;">Brand</th>
												<th style="padding:4px 6px;font-size:11px;">Warranty</th>
												<th style="padding:4px 6px;font-size:11px;">Watt / Volt</th>
												<th style="padding:4px 6px;font-size:11px;">Total No. of Pieces</th>
											</tr>
										</thead>
										<tbody style="font-size:11px;">
											<?php
											$i = 1;
											if (count($products) > 0) {
												foreach ($products as $product) { ?>
													<tr>
														<td style="padding:4px 6px;font-size:11px;"><?php echo $i; ?></td>
														<td style="padding:4px 6px;font-size:11px;"><?php echo $product->product_name; ?></td>
														<td style="padding:4px 6px;font-size:11px;"><?php echo $product->brand_name; ?></td>
														<td style="padding:4px 6px;font-size:11px;"><?php echo $product->warranty; ?></td>
														<td style="padding:4px 6px;font-size:11px;">NA</td>
														<td style="padding:4px 6px;font-size:11px;">NA</td>
													</tr>
													<?php $i++;
												}
											} ?>
										</tbody>
									</table>
								</div>
							</div>

							<!-- ========================================================= -->
							<!--  PAGE 5  –– full-page background  (xyzLast.jpg)         -->
							<!-- ========================================================= -->
							<div class="row pagebreak" style="position:relative;width:210mm;height:297mm;margin:0 auto;page-break-before:always;">
								<img src="<?php echo base_url()?>assets/media/qutation-design/5.jpg"
									style="position:absolute;top:0;left:0;width:100%;height:100%;object-fit:cover;">
								<!-- =====  put your custom content here  ===== -->
							</div>
							<div class="d-flex flex-stack flex-wrap mt-lg-20 pt-8">
								<!-- begin::Actions-->
								<div class="d-flex flex-stack flex-wrap mt-lg-20 pt-8 no-print">
									<button type="button" class="btn btn-success my-1 me-12" onclick="window.print();">Print Invoice</button>
								</div>
								<!-- end::Actions-->
								<!-- BUTTON –– always visible, print par bhi bottom-right -->

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

