<style>
    @media print {
        .pagebreak { page-break-before: always; } /* page-break-after works, as well */
    }
    .table > :not(caption) > * > * {
        padding: .25em .25rem;
    }
    
    .row {
      overflow: hidden;
      position: relative;
    }
    
    .demo-bg {
      opacity: 0.2;
      position: absolute;
      left: 10%;
      top: 22%;
      width: 85%;
      height: auto;
    }    
    .water {
      position: relative;
    }
    
</style>

					<!--begin::Content-->
					<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
						<!--begin::Post-->
						<div class="post d-flex flex-column-fluid" id="kt_post">
							<!--begin::Container-->
							<div id="kt_content_container" class="container-xxl">
								<!-- begin::Invoice 3-->
								<div class="card" style="border:none;">
									<!-- begin::Body-->
									<div class="card-body py-2">
									    <div class="row">
									        <img class="demo-bg" src="<?php echo base_url()?>assets/media/scopnix-logo-watermark.jpeg" alt="">
										    <!-- begin::Wrapper-->
										    <div class="mw-lg-1100px mx-auto w-100 water">
    											<!-- begin::Header-->
    											<div class="d-flex justify-content-between flex-column flex-sm-row mb-8" style="border-bottom: solid;">
    												<!--begin::Logo-->
    												<a href="#" class="d-block mw-100px">
    													<img alt="Logo" src="<?php echo base_url()?>assets/media/logos/icon.png" class="w-100" />
    												</a>
    												<div class="d-block col-10">
    												    <h2 class="fs-2 text-center">SCOPNIX SOLAR ENERGY & EV</h2>
    												    <p class="fs-4 text-muted"><?php echo strip_tags($settings->address);?></p>
    													<table class="text-muted table-responsive table" style="width:100%;">
    													    <tr>
    													        <td style="width:50%;" class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">Mobile:-</span><?php echo $settings->mobile1;?></td>
    													        <td style="width:50%;" class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">Email:-</span><?php echo $settings->email;?></td>
    													    </tr>
    													    <tr>
    													        <td class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">CIN:-</span><?php echo $settings->cin_no;?></td>
    													        <td class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">GST:-</span><?php echo $settings->gst_no;?></td>
    													    </tr>
    													</table>    
    													<!--end::Text-->
    												</div>
    											</div>
    											
    											<!--end::Header-->
    											<div class="d-flex justify-content-between flex-column flex-sm-row">
    												<div class="text-sm col-7">
        												<table class="text-muted table-responsive table" style="width:100%;">
        												    <tr><th class="min-w-100px"><span class="fw-bold text-gray-800">Name:-</span></th> <td><?php echo $client->client_name;?></td></tr>
        												    <tr><th><span class="fw-bold text-gray-800">Mobile:-</span></th> <td><?php echo $client->phone;?></td></tr>
        												    <tr><th><span class="fw-bold text-gray-800">Address:-</span></th> <td><?php echo $client->address;?></td></tr>
        												</table>    
    											    </div>
    											    <div class="text-sm col-5">
        												<table class="text-muted table-responsive table" style="width:100%;">
        												    <tr><th class="min-w-100px"><span class="fw-bold text-gray-800">Generated By:-</span></th> <td><?php echo $franchisee->franchisee_code;?></td></tr>
        												    <tr><th class="min-w-100px"><span class="fw-bold text-gray-800">Vendor Name:-</span></th> <td><?php echo $vendor->vendor_name;?></td></tr>
        												    <tr><th><span class="fw-bold text-gray-800">Quatation No:-</span></th> <td><?php echo $data_info->reference_no;?></td></tr>
        												    <tr><th><span class="fw-bold text-gray-800">Date:-</span></th> <td><?php echo date('d-m-Y',strtotime($data_info->qauote_date));?></td></tr>
        												</table>    
        											</div>	
    											</div>	
    											<!--begin::Body-->
    											<div class="pb-2">
    												<!--begin::Wrapper-->
    												<div class="d-flex flex-column gap-7">
    													<!--begin::Separator-->
    													<div class="separator"></div>
    													<!--begin::Separator-->
    													<!--begin::Separator-->
                                                        <div class="fw-bold fs-2">About Scopnix Solar:
    													    <span class="text-muted fs-5">
    													        <p>At Scopnix, we’re on a mission to bring sustainable, reliable, and affordable solar energy solutions to homes, businesses, and communities across the country. With a firm commitment to quality and customer satisfaction, we offer a comprehensive range of solar products and services, from residential rooftop systems to commercial solar installations.</p>
                                                                <p>Our goal is to help you reduce energy costs, decrease dependence on traditional power sources, and contribute to a cleaner, greener planet.</p>
                                                            </span>
    													</div>
                                                        <div class="fw-bold fs-2">SCOPNIX SOLAR ENERGY & EV:
    													   <span class="text-muted fs-5">
    													     <p>Scopnix’s brand voice is empowering, knowledgeable, and approachable. We speak with confidence about the benefits of solar energy, making complex topics understandable for our customers. Whether educating on the technical aspects or highlighting the environmental impact, we communicate in a friendly, inspiring, and straightforward manner.</p>
    													       <div class="why-features-desc">
                                									<h3>Customer Empowerment</h3>
                                									<p>Scopnix believes in giving our customers the tools and knowledge they need to make informed energy decisions. We provide transparent information, thorough education, and consistent support throughout the solar journey.</p>
                                								</div> 
                                								
                                                                <div class="why-features-desc">
                                									<h3>Sustainability</h3>
                                									<p>We’re committed to reducing carbon footprints and creating a positive environmental impact by promoting solar energy. Every Scopnix installation supports cleaner air, reduces greenhouse gas emissions, and contributes to a healthier planet.</p>
                                								</div>  
                                								
                                								<div class="why-features-desc">
                                									<h3>Community Focus</h3>
                                									<p>Scopnix is more than just a solar provider; we’re a community partner. We work closely with local communities and government initiatives to bring solar energy where it’s needed most, supporting local economies and driving sustainable progress.</p>
                                								</div>
    													   </span>
    													</div>
    												</div>
    												<!--end::Wrapper-->
    											</div>
    											<!--end::Body-->
    										</div>
    										    <!-- end::Wrapper-->
										</div>
										<div class="separator"></div>
									    <div class="row watermark pagebreak">
									        <img class="demo-bg" src="<?php echo base_url()?>assets/media/scopnix-logo-watermark.jpeg" alt="">
										    <!-- begin::Wrapper-->
										    <div class="mw-lg-1100px mx-auto w-100 water">
    											<!-- begin::Header-->
    											<div class="d-flex justify-content-between flex-column flex-sm-row mb-8" style="border-bottom: solid;">
    												<!--begin::Logo-->
    												<a href="#" class="d-block mw-100px">
    													<img alt="Logo" src="<?php echo base_url()?>assets/media/logos/icon.png" class="w-100" />
    												</a>
    												<div class="d-block col-10">
    												    <h2 class="fs-2 text-center">SCOPNIX SOLAR ENERGY & EV</h2>
    												    <p class="fs-4 text-muted"><?php echo strip_tags($settings->address);?></p>
    													<table class="text-muted table-responsive table" style="width:100%;">
    													    <tr>
    													        <td style="width:50%;" class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">Mobile:-</span><?php echo $settings->mobile1;?></td>
    													        <td style="width:50%;" class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">Email:-</span><?php echo $settings->email;?></td>
    													    </tr>
    													    <tr>
    													        <td class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">CIN:-</span><?php echo $settings->cin_no;?></td>
    													        <td class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">GST:-</span><?php echo $settings->gst_no;?></td>
    													    </tr>
    													</table>    
    													<!--end::Text-->
    												</div>
    											</div>
    											<!--end::Header-->
    											<!--begin::Body-->
    											<div class="pb-2">
    												<!--begin::Wrapper-->
    												<div class="d-flex flex-column gap-7">
    													<!--begin::Message-->
    													<div class="fw-bold fs-4 text-sm text-muted">
    												        <span class="fw-bold text-gray-800">Project:</span> <?php echo $project->project_name;?><br>
    												        <span style="margin-right:30px;"><span class="fw-bold text-gray-800">Project Size:</span> <?php echo $project->qty;?> KW</span>
    												        <span class="fw-bold text-gray-800">Project Type:</span> <?php echo $project->project_type;?><br><br>
    												    
    												        <span class="fw-bold text-gray-800">Price:</span> &#8377;. <?php echo $project->basic_rate;?> /KW<br>
    												        <span class="fw-bold text-gray-800">Special Discount:</span> &#8377;. ______________________________ <br>
    													    <span class="fw-bold text-gray-800">Total Price:</span> &#8377;. <?php echo $project->amount;?> <br>
    													    
    													    <br><span class="fw-bold text-gray-800">Scope of Work:</span> <?php echo $data_info->work_scope;?>
    													    <br><span class="fw-bold text-gray-800">Specification:</span> <?php echo $data_info->specification;?><br>
    													</div>
    													<!--begin::Message-->
    													<!--begin::Separator-->
    													<div class="separator"></div>
    													<!--begin::Separator-->
                                                        <div class="fw-bold fs-2">Payment Details:
    													    <span class="text-muted fs-5"><?php echo $settings->bank_details;?></span>
    													</div>
    													<!--begin::Separator-->
    													<div class="separator"></div>
    													<!--begin::Separator-->
                                                        <div class="fw-bold fs-2">Terms & Conditions:
    													    <span class="text-muted fs-5"><?php echo $settings->quote_terms;?></span>
    													</div>
    													<div class="separator border-5 border-info my-5"></div>
    													<!--begin:Order summary-->
    													<div class="d-flex justify-content-between flex-column">
    														<!--begin::Table-->
    														<div class="table-responsive mb-3">
    														    <table>
    														        <tr>
            														    <td style="width:75%;"><span class="text-muted fs-5"><?php echo $settings->quote_footer?></span></td>
            														    <td class="text-sm-end">
                														    <span class="fw-bold fs-3">Visit US</span><br>
                														    <span class="text-muted fs-5"><?php echo $settings->website?></span>
                														</td>    
            														</tr>    
        														</table>    
    														</div>
    														<!--end::Table-->
    													</div>
    													<!--end:Order summary-->
    												</div>
    												<!--end::Wrapper-->
    											</div>
    											<!--end::Body-->
    										</div>
    										    <!-- end::Wrapper-->
										</div>
									    <div class="separator"></div>
									    <div class="row pagebreak watermark">
									        <img class="demo-bg" src="<?php echo base_url()?>assets/media/scopnix-logo-watermark.jpeg" alt="">
										    <!-- begin::Wrapper-->
										    <div class="mw-lg-1100px mx-auto w-100 water">
    											<!-- begin::Header-->
    											<div class="d-flex justify-content-between flex-column flex-sm-row mb-8" style="border-bottom: solid;">
    												<!--begin::Logo-->
    												<a href="#" class="d-block mw-100px">
    													<img alt="Logo" src="<?php echo base_url()?>assets/media/logos/icon.png" class="w-100" />
    												</a>
    												<div class="d-block col-10">
    												    <h2 class="fs-2 text-center">SCOPNIX SOLAR ENERGY & EV</h2>
    												    <p class="fs-4 text-muted"><?php echo strip_tags($settings->address);?></p>
    													<table class="text-muted table-responsive table" style="width:100%;">
    													    <tr>
    													        <td style="width:50%;" class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">Mobile:-</span><?php echo $settings->mobile1;?></td>
    													        <td style="width:50%;" class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">Email:-</span><?php echo $settings->email;?></td>
    													    </tr>
    													    <tr>
    													        <td class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">CIN:-</span><?php echo $settings->cin_no;?></td>
    													        <td class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">GST:-</span><?php echo $settings->gst_no;?></td>
    													    </tr>
    													</table>    
    													<!--end::Text-->
    												</div>
    											</div>
    											<!--end::Header-->
    											<!--begin::Body-->
    											<div class="pb-4">
    												<!--begin::Wrapper-->
    												<div class="d-flex flex-column gap-7">
    													<div class="d-flex justify-content-between flex-column">
    														<p class="fs-4 text-muted">Solar Panal ______________________________________________ <br> Inverter ______________________________________________</p>
    														<!--begin::Table-->
                                                            <div class="table-responsive" style="height:630px">
                                                                <table class="table table-bordered align-middle mb-0">
                                                                    <thead class="table-light">
                                                                        <tr>
                                                                            <th scope="col">#</th>
                                                                            <th scope="col" style="width:60%;">Product Name</th>
                                                                            <th scope="col" style="width:30%;">Brand</th>
                                                                            <th scope="col">Warranty</th>
                                                                        </tr>
                                                                    </thead>
                                                                    <tbody>
                                                                        <?php 
                                                                        $i=1;
                                                                        if(count($products) > 0) {
                                                                            foreach($products as $product) { ?>
                                                                            <tr>
                                                                                <td><?php echo $i;?></td>
                                                                                <td><?php echo $product->product_name;?></td>
                                                                                <td><?php echo $product->brand_name;?></td>
                                                                                <td><?php echo $product->warranty;?></td>
                                                                            </tr>
                                                                            <?php $i++;
                                                                            }
                                                                        } ?>    
                                                                    </tbody>
                                                                </table>
                                                                <!-- end table -->
                                                            </div>
                                                            <!-- end table responsive -->
    													</div>
    													<!--end:Order summary-->
    													<div class="separator border-5 border-info my-5"></div>
    													<!--begin:Order summary-->
    													<div class="d-flex justify-content-between flex-column">
    														<!--begin::Table-->
    														<div class="table-responsive mb-3">
    														    <table>
    														        <tr>
            														    <td style="width:75%;"><span class="text-muted fs-5"><?php echo $settings->quote_footer?></span></td>
            														    <td class="text-sm-end">
                														    <span class="fw-bold fs-3">Visit US</span><br>
                														    <span class="text-muted fs-5"><?php echo $settings->website?></span>
                														</td>    
            														</tr>    
        														</table>    
    														</div>
    														<!--end::Table-->
    													</div>
    													<!--end:Order summary-->
    												    	
    												</div>
    												<!--end::Wrapper-->
    												
    											</div>
    											<!--end::Body-->
										    </div>
										    <!-- end::Wrapper-->
										</div>
									    <div class="row pagebreak">
										    <!-- begin::Wrapper-->
										    <div class="mw-lg-1100px mx-auto w-100">
    											<!-- begin::Header-->
    											<div class="d-flex justify-content-between flex-column flex-sm-row mb-8" style="border-bottom: solid;">
    												<!--begin::Logo-->
    												<a href="#" class="d-block mw-100px">
    													<img alt="Logo" src="<?php echo base_url()?>assets/media/logos/icon.png" class="w-100" />
    												</a>
    												<div class="d-block col-10">
    												    <h2 class="fs-2 text-center">SCOPNIX SOLAR ENERGY & EV</h2>
    												    <p class="fs-4 text-muted"><?php echo strip_tags($settings->address);?></p>
    													<table class="text-muted table-responsive table" style="width:100%;">
    													    <tr>
    													        <td style="width:50%;" class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">Mobile:-</span><?php echo $settings->mobile1;?></td>
    													        <td style="width:50%;" class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">Email:-</span><?php echo $settings->email;?></td>
    													    </tr>
    													    <tr>
    													        <td class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">CIN:-</span><?php echo $settings->cin_no;?></td>
    													        <td class="min-w-100px"><span class="fw-bold text-gray-800" style="margin-right:15px;">GST:-</span><?php echo $settings->gst_no;?></td>
    													    </tr>
    													</table>    
    													<!--end::Text-->
    												</div>
    											</div>
    											<!--end::Header-->
    											<!--begin::Body-->
    											<div class="">'
    											    <img src="<?php echo base_url();?>/assets/media/<?php echo $project->project_image;?>" width="100%" height="700">
    											</div>
    											<!--end::Body-->
												<div class="separator border-5 border-info my-5"></div>
												<!--begin:Order summary-->
												<div class="d-flex justify-content-between flex-column">
													<!--begin::Table-->
													<div class="table-responsive mb-3">
													    <table>
													        <tr>
    														    <td style="width:75%;"><span class="text-muted fs-5"><?php echo $settings->quote_footer?></span></td>
    														    <td class="text-sm-end">
        														    <span class="fw-bold fs-3">Visit US</span><br>
        														    <span class="text-muted fs-5"><?php echo $settings->website?></span>
        														</td>    
    														</tr>    
														</table>    
													</div>
													<!--end::Table-->
												</div>
												<!--end:Order summary-->


    											<!-- begin::Footer-->
    											<div class="d-flex flex-stack flex-wrap mt-lg-20 pt-8">
    												<!-- begin::Actions-->
    												<div class="my-1 me-5">
    													<!-- begin::Pint-->
    													<button type="button" class="btn btn-success my-1 me-12" onclick="window.print();">Print Invoice</button>
    													<!-- end::Pint-->
    												</div>
    												<!-- end::Actions-->
    											</div>
    											<!-- end::Footer-->
										    </div>
										    <!-- end::Wrapper-->
										</div>


									</div>
									<!-- end::Body-->
								</div>
								<!-- end::Invoice 1-->
							</div>
							<!--end::Container-->
						</div>
						<!--end::Post-->
					</div>
					<!--end::Content-->
